apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: checkoutservice
        image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-checkout-service:latest
        ports:
        - containerPort: 5050
          name: grpc
        env:
        - name: PORT
          value: "5050"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "product-catalog-service:3550"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
    protocol: TCP