apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: product-catalog-service
        image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-product-catalog-service:latest
        ports:
        - containerPort: 3550
          name: http
        env:
        - name: PORT
          value: "3550"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  type: ClusterIP
  selector:
    app: product-catalog-service
  ports:
  - name: http
    port: 3550
    targetPort: 3550
    protocol: TCP